/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_Mcu.h"

static const char* CMockString_Mcu_GetSystemTime_u32 = "Mcu_GetSystemTime_u32";
static const char* CMockString_Mcu_Initialize = "Mcu_Initialize";
static const char* CMockString_Mcu_ReloadSystick = "Mcu_ReloadSystick";
static const char* CMockString_Mcu_ServiceWatchdogSow = "Mcu_ServiceWatchdogSow";

typedef struct _CMOCK_Mcu_Initialize_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int CallOrder;

} CMOCK_Mcu_Initialize_CALL_INSTANCE;

typedef struct _CMOCK_Mcu_ServiceWatchdogSow_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int CallOrder;

} CMOCK_Mcu_ServiceWatchdogSow_CALL_INSTANCE;

typedef struct _CMOCK_Mcu_ReloadSystick_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int CallOrder;

} CMOCK_Mcu_ReloadSystick_CALL_INSTANCE;

typedef struct _CMOCK_Mcu_GetSystemTime_u32_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint32_t ReturnVal;
  int CallOrder;

} CMOCK_Mcu_GetSystemTime_u32_CALL_INSTANCE;

static struct mock_McuInstance
{
  char Mcu_Initialize_IgnoreBool;
  char Mcu_Initialize_CallbackBool;
  CMOCK_Mcu_Initialize_CALLBACK Mcu_Initialize_CallbackFunctionPointer;
  int Mcu_Initialize_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE Mcu_Initialize_CallInstance;
  char Mcu_ServiceWatchdogSow_IgnoreBool;
  char Mcu_ServiceWatchdogSow_CallbackBool;
  CMOCK_Mcu_ServiceWatchdogSow_CALLBACK Mcu_ServiceWatchdogSow_CallbackFunctionPointer;
  int Mcu_ServiceWatchdogSow_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE Mcu_ServiceWatchdogSow_CallInstance;
  char Mcu_ReloadSystick_IgnoreBool;
  char Mcu_ReloadSystick_CallbackBool;
  CMOCK_Mcu_ReloadSystick_CALLBACK Mcu_ReloadSystick_CallbackFunctionPointer;
  int Mcu_ReloadSystick_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE Mcu_ReloadSystick_CallInstance;
  char Mcu_GetSystemTime_u32_IgnoreBool;
  uint32_t Mcu_GetSystemTime_u32_FinalReturn;
  char Mcu_GetSystemTime_u32_CallbackBool;
  CMOCK_Mcu_GetSystemTime_u32_CALLBACK Mcu_GetSystemTime_u32_CallbackFunctionPointer;
  int Mcu_GetSystemTime_u32_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE Mcu_GetSystemTime_u32_CallInstance;
} Mock;

extern int GlobalExpectCount;
extern int GlobalVerifyOrder;

void mock_Mcu_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.Mcu_Initialize_CallInstance;
  if (Mock.Mcu_Initialize_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_Mcu_Initialize);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.Mcu_Initialize_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.Mcu_ServiceWatchdogSow_CallInstance;
  if (Mock.Mcu_ServiceWatchdogSow_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_Mcu_ServiceWatchdogSow);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.Mcu_ServiceWatchdogSow_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.Mcu_ReloadSystick_CallInstance;
  if (Mock.Mcu_ReloadSystick_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_Mcu_ReloadSystick);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.Mcu_ReloadSystick_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.Mcu_GetSystemTime_u32_CallInstance;
  if (Mock.Mcu_GetSystemTime_u32_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_Mcu_GetSystemTime_u32);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.Mcu_GetSystemTime_u32_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_Mcu_Init(void)
{
  mock_Mcu_Destroy();
}

void mock_Mcu_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
}

void Mcu_Initialize(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Mcu_Initialize_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_Mcu_Initialize);
  cmock_call_instance = (CMOCK_Mcu_Initialize_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.Mcu_Initialize_CallInstance);
  Mock.Mcu_Initialize_CallInstance = CMock_Guts_MemNext(Mock.Mcu_Initialize_CallInstance);
  if (Mock.Mcu_Initialize_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.Mcu_Initialize_CallbackBool &&
      Mock.Mcu_Initialize_CallbackFunctionPointer != NULL)
  {
    Mock.Mcu_Initialize_CallbackFunctionPointer(Mock.Mcu_Initialize_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (Mock.Mcu_Initialize_CallbackFunctionPointer != NULL)
  {
    Mock.Mcu_Initialize_CallbackFunctionPointer(Mock.Mcu_Initialize_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void Mcu_Initialize_CMockIgnore(void)
{
  Mock.Mcu_Initialize_IgnoreBool = (char)1;
}

void Mcu_Initialize_CMockStopIgnore(void)
{
  Mock.Mcu_Initialize_IgnoreBool = (char)0;
}

void Mcu_Initialize_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Mcu_Initialize_CALL_INSTANCE));
  CMOCK_Mcu_Initialize_CALL_INSTANCE* cmock_call_instance = (CMOCK_Mcu_Initialize_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Mcu_Initialize_CallInstance = CMock_Guts_MemChain(Mock.Mcu_Initialize_CallInstance, cmock_guts_index);
  Mock.Mcu_Initialize_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

void Mcu_Initialize_AddCallback(CMOCK_Mcu_Initialize_CALLBACK Callback)
{
  Mock.Mcu_Initialize_IgnoreBool = (char)0;
  Mock.Mcu_Initialize_CallbackBool = (char)1;
  Mock.Mcu_Initialize_CallbackFunctionPointer = Callback;
}

void Mcu_Initialize_Stub(CMOCK_Mcu_Initialize_CALLBACK Callback)
{
  Mock.Mcu_Initialize_IgnoreBool = (char)0;
  Mock.Mcu_Initialize_CallbackBool = (char)0;
  Mock.Mcu_Initialize_CallbackFunctionPointer = Callback;
}

void Mcu_ServiceWatchdogSow(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Mcu_ServiceWatchdogSow_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_Mcu_ServiceWatchdogSow);
  cmock_call_instance = (CMOCK_Mcu_ServiceWatchdogSow_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.Mcu_ServiceWatchdogSow_CallInstance);
  Mock.Mcu_ServiceWatchdogSow_CallInstance = CMock_Guts_MemNext(Mock.Mcu_ServiceWatchdogSow_CallInstance);
  if (Mock.Mcu_ServiceWatchdogSow_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.Mcu_ServiceWatchdogSow_CallbackBool &&
      Mock.Mcu_ServiceWatchdogSow_CallbackFunctionPointer != NULL)
  {
    Mock.Mcu_ServiceWatchdogSow_CallbackFunctionPointer(Mock.Mcu_ServiceWatchdogSow_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (Mock.Mcu_ServiceWatchdogSow_CallbackFunctionPointer != NULL)
  {
    Mock.Mcu_ServiceWatchdogSow_CallbackFunctionPointer(Mock.Mcu_ServiceWatchdogSow_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void Mcu_ServiceWatchdogSow_CMockIgnore(void)
{
  Mock.Mcu_ServiceWatchdogSow_IgnoreBool = (char)1;
}

void Mcu_ServiceWatchdogSow_CMockStopIgnore(void)
{
  Mock.Mcu_ServiceWatchdogSow_IgnoreBool = (char)0;
}

void Mcu_ServiceWatchdogSow_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Mcu_ServiceWatchdogSow_CALL_INSTANCE));
  CMOCK_Mcu_ServiceWatchdogSow_CALL_INSTANCE* cmock_call_instance = (CMOCK_Mcu_ServiceWatchdogSow_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Mcu_ServiceWatchdogSow_CallInstance = CMock_Guts_MemChain(Mock.Mcu_ServiceWatchdogSow_CallInstance, cmock_guts_index);
  Mock.Mcu_ServiceWatchdogSow_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

void Mcu_ServiceWatchdogSow_AddCallback(CMOCK_Mcu_ServiceWatchdogSow_CALLBACK Callback)
{
  Mock.Mcu_ServiceWatchdogSow_IgnoreBool = (char)0;
  Mock.Mcu_ServiceWatchdogSow_CallbackBool = (char)1;
  Mock.Mcu_ServiceWatchdogSow_CallbackFunctionPointer = Callback;
}

void Mcu_ServiceWatchdogSow_Stub(CMOCK_Mcu_ServiceWatchdogSow_CALLBACK Callback)
{
  Mock.Mcu_ServiceWatchdogSow_IgnoreBool = (char)0;
  Mock.Mcu_ServiceWatchdogSow_CallbackBool = (char)0;
  Mock.Mcu_ServiceWatchdogSow_CallbackFunctionPointer = Callback;
}

void Mcu_ReloadSystick(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Mcu_ReloadSystick_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_Mcu_ReloadSystick);
  cmock_call_instance = (CMOCK_Mcu_ReloadSystick_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.Mcu_ReloadSystick_CallInstance);
  Mock.Mcu_ReloadSystick_CallInstance = CMock_Guts_MemNext(Mock.Mcu_ReloadSystick_CallInstance);
  if (Mock.Mcu_ReloadSystick_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.Mcu_ReloadSystick_CallbackBool &&
      Mock.Mcu_ReloadSystick_CallbackFunctionPointer != NULL)
  {
    Mock.Mcu_ReloadSystick_CallbackFunctionPointer(Mock.Mcu_ReloadSystick_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (Mock.Mcu_ReloadSystick_CallbackFunctionPointer != NULL)
  {
    Mock.Mcu_ReloadSystick_CallbackFunctionPointer(Mock.Mcu_ReloadSystick_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void Mcu_ReloadSystick_CMockIgnore(void)
{
  Mock.Mcu_ReloadSystick_IgnoreBool = (char)1;
}

void Mcu_ReloadSystick_CMockStopIgnore(void)
{
  Mock.Mcu_ReloadSystick_IgnoreBool = (char)0;
}

void Mcu_ReloadSystick_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Mcu_ReloadSystick_CALL_INSTANCE));
  CMOCK_Mcu_ReloadSystick_CALL_INSTANCE* cmock_call_instance = (CMOCK_Mcu_ReloadSystick_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Mcu_ReloadSystick_CallInstance = CMock_Guts_MemChain(Mock.Mcu_ReloadSystick_CallInstance, cmock_guts_index);
  Mock.Mcu_ReloadSystick_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

void Mcu_ReloadSystick_AddCallback(CMOCK_Mcu_ReloadSystick_CALLBACK Callback)
{
  Mock.Mcu_ReloadSystick_IgnoreBool = (char)0;
  Mock.Mcu_ReloadSystick_CallbackBool = (char)1;
  Mock.Mcu_ReloadSystick_CallbackFunctionPointer = Callback;
}

void Mcu_ReloadSystick_Stub(CMOCK_Mcu_ReloadSystick_CALLBACK Callback)
{
  Mock.Mcu_ReloadSystick_IgnoreBool = (char)0;
  Mock.Mcu_ReloadSystick_CallbackBool = (char)0;
  Mock.Mcu_ReloadSystick_CallbackFunctionPointer = Callback;
}

uint32_t Mcu_GetSystemTime_u32(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Mcu_GetSystemTime_u32_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_Mcu_GetSystemTime_u32);
  cmock_call_instance = (CMOCK_Mcu_GetSystemTime_u32_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.Mcu_GetSystemTime_u32_CallInstance);
  Mock.Mcu_GetSystemTime_u32_CallInstance = CMock_Guts_MemNext(Mock.Mcu_GetSystemTime_u32_CallInstance);
  if (Mock.Mcu_GetSystemTime_u32_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.Mcu_GetSystemTime_u32_FinalReturn;
    Mock.Mcu_GetSystemTime_u32_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.Mcu_GetSystemTime_u32_CallbackBool &&
      Mock.Mcu_GetSystemTime_u32_CallbackFunctionPointer != NULL)
  {
    uint32_t cmock_cb_ret = Mock.Mcu_GetSystemTime_u32_CallbackFunctionPointer(Mock.Mcu_GetSystemTime_u32_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (Mock.Mcu_GetSystemTime_u32_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.Mcu_GetSystemTime_u32_CallbackFunctionPointer(Mock.Mcu_GetSystemTime_u32_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void Mcu_GetSystemTime_u32_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Mcu_GetSystemTime_u32_CALL_INSTANCE));
  CMOCK_Mcu_GetSystemTime_u32_CALL_INSTANCE* cmock_call_instance = (CMOCK_Mcu_GetSystemTime_u32_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Mcu_GetSystemTime_u32_CallInstance = CMock_Guts_MemChain(Mock.Mcu_GetSystemTime_u32_CallInstance, cmock_guts_index);
  Mock.Mcu_GetSystemTime_u32_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.Mcu_GetSystemTime_u32_IgnoreBool = (char)1;
}

void Mcu_GetSystemTime_u32_CMockStopIgnore(void)
{
  if(Mock.Mcu_GetSystemTime_u32_IgnoreBool)
    Mock.Mcu_GetSystemTime_u32_CallInstance = CMock_Guts_MemNext(Mock.Mcu_GetSystemTime_u32_CallInstance);
  Mock.Mcu_GetSystemTime_u32_IgnoreBool = (char)0;
}

void Mcu_GetSystemTime_u32_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Mcu_GetSystemTime_u32_CALL_INSTANCE));
  CMOCK_Mcu_GetSystemTime_u32_CALL_INSTANCE* cmock_call_instance = (CMOCK_Mcu_GetSystemTime_u32_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Mcu_GetSystemTime_u32_CallInstance = CMock_Guts_MemChain(Mock.Mcu_GetSystemTime_u32_CallInstance, cmock_guts_index);
  Mock.Mcu_GetSystemTime_u32_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void Mcu_GetSystemTime_u32_AddCallback(CMOCK_Mcu_GetSystemTime_u32_CALLBACK Callback)
{
  Mock.Mcu_GetSystemTime_u32_IgnoreBool = (char)0;
  Mock.Mcu_GetSystemTime_u32_CallbackBool = (char)1;
  Mock.Mcu_GetSystemTime_u32_CallbackFunctionPointer = Callback;
}

void Mcu_GetSystemTime_u32_Stub(CMOCK_Mcu_GetSystemTime_u32_CALLBACK Callback)
{
  Mock.Mcu_GetSystemTime_u32_IgnoreBool = (char)0;
  Mock.Mcu_GetSystemTime_u32_CallbackBool = (char)0;
  Mock.Mcu_GetSystemTime_u32_CallbackFunctionPointer = Callback;
}

