@startuml inline_umlgraph_1.svg
start
:l_idx_u32 = 0;
while (l_idx_u32 < SCHED_NUM_OF_TASKS) is (yes)
  :compute l_timeShift_s32;
  if (l_timeShift_s32 >= 0) then (yes)
    :call handler_();
    :NumOfTaskCalls_au32[idx]++;
  else (no)
  endif
  :l_idx_u32++;
endwhile
:return;
stop
@enduml
@startuml inline_umlgraph_2.svg
start
:l_idx_u32 = 0;
while (l_idx_u32 < SCHED_NUM_OF_TASKS) is (yes)
  :compute l_timeShift_s32;
  if (l_timeShift_s32 >= 0) then (yes)
    :call handler_();
    :NumOfTaskCalls_au32[idx]++;
  else (no)
  endif
  :l_idx_u32++;
endwhile
:return;
stop
@enduml
@startuml inline_umlgraph_3.svg
start
:l_idx_u32 = 0;
while (l_idx_u32 < SCHED_NUM_OF_TASKS) is (yes)
  :compute l_timeShift_s32;
  if (l_timeShift_s32 >= 0) then (yes)
    :call handler_();
    :NumOfTaskCalls_au32[idx]++;
  else (no)
  endif
  :l_idx_u32++;
endwhile
:return;
stop
@enduml
@startuml inline_umlgraph_4.svg
start
:Mcu_Initialize();
:Mcu_ServiceWatchdogSow();
:Mcu_ReloadSystick();
stop
@enduml
@startuml inline_umlgraph_5.svg
start
:Mcu_Initialize();
:Mcu_ServiceWatchdogSow();
:Mcu_ReloadSystick();
stop
@enduml
@startuml inline_umlgraph_6.svg
start
:Mcu_Initialize();
:Mcu_ServiceWatchdogSow();
:Mcu_ReloadSystick();
stop
@enduml
@startuml inline_umlgraph_7.svg
start
:Mcu_Initialize();
:Mcu_ServiceWatchdogSow();
:Mcu_ReloadSystick();
stop
@enduml
@startuml inline_umlgraph_8.svg
start
:Mcu_Initialize();
:Mcu_ServiceWatchdogSow();
:Mcu_ReloadSystick();
stop
@enduml
@startuml inline_umlgraph_9.svg
start
:Mcu_Initialize();
:Mcu_ServiceWatchdogSow();
:Mcu_ReloadSystick();
stop
@enduml
@startuml inline_umlgraph_10.svg
start
:Mcu_Initialize();
:Mcu_ServiceWatchdogSow();
:Mcu_ReloadSystick();
stop
@enduml
@startuml inline_umlgraph_11.svg
start
:Mcu_Initialize();
:Mcu_ServiceWatchdogSow();
:Mcu_ReloadSystick();
stop
@enduml
@startuml inline_umlgraph_12.svg
start
:Mcu_Initialize();
:Mcu_ServiceWatchdogSow();
:Mcu_ReloadSystick();
stop
@enduml
@startuml inline_umlgraph_13.svg
start
:Mcu_Initialize();
:Mcu_ServiceWatchdogSow();
:Mcu_ReloadSystick();
stop
@enduml
@startuml inline_umlgraph_14.svg
start
:Mcu_Initialize();
:Mcu_ServiceWatchdogSow();
:Mcu_ReloadSystick();
stop
@enduml
@startuml inline_umlgraph_15.svg
start
:Mcu_Initialize();
:Mcu_ServiceWatchdogSow();
:Mcu_ReloadSystick();
stop
@enduml
@startuml inline_umlgraph_16.svg
start
:Mcu_Initialize();
:Mcu_ServiceWatchdogSow();
:Mcu_ReloadSystick();
stop
@enduml
@startuml inline_umlgraph_17.svg
start
:l_idx_u32 = 0;
while (l_idx_u32 < SCHED_NUM_OF_TASKS) is (yes)
  :compute l_timeShift_s32;
  if (l_timeShift_s32 >= 0) then (yes)
    :call handler_();
    :NumOfTaskCalls_au32[idx]++;
  else (no)
  endif
  :l_idx_u32++;
endwhile
:return;
stop
@enduml
@startuml inline_umlgraph_18.svg
start
:l_idx_u32 = 0;
while (l_idx_u32 < SCHED_NUM_OF_TASKS) is (yes)
  :compute l_timeShift_s32;
  if (l_timeShift_s32 >= 0) then (yes)
    :call handler_();
    :NumOfTaskCalls_au32[idx]++;
  else (no)
  endif
  :l_idx_u32++;
endwhile
:return;
stop
@enduml
@startuml inline_umlgraph_19.svg
start
:l_idx_u32 = 0;
while (l_idx_u32 < SCHED_NUM_OF_TASKS) is (yes)
  :compute l_timeShift_s32;
  if (l_timeShift_s32 >= 0) then (yes)
    :call handler_();
    :NumOfTaskCalls_au32[idx]++;
  else (no)
  endif
  :l_idx_u32++;
endwhile
:return;
stop
@enduml
@startuml inline_umlgraph_20.svg
start
:l_idx_u32 = 0;
while (l_idx_u32 < SCHED_NUM_OF_TASKS) is (yes)
  :compute l_timeShift_s32;
  if (l_timeShift_s32 >= 0) then (yes)
    :call handler_();
    :NumOfTaskCalls_au32[idx]++;
  else (no)
  endif
  :l_idx_u32++;
endwhile
:return;
stop
@enduml
@startuml inline_umlgraph_21.svg
start
:l_idx_u32 = 0;
while (l_idx_u32 < SCHED_NUM_OF_TASKS) is (yes)
  :compute l_timeShift_s32;
  if (l_timeShift_s32 >= 0) then (yes)
    :call handler_();
    :NumOfTaskCalls_au32[idx]++;
  else (no)
  endif
  :l_idx_u32++;
endwhile
:return;
stop
@enduml
@startuml inline_umlgraph_22.svg
start
:l_idx_u32 = 0;
while (l_idx_u32 < SCHED_NUM_OF_TASKS) is (yes)
  :compute l_timeShift_s32;
  if (l_timeShift_s32 >= 0) then (yes)
    :call handler_();
    :NumOfTaskCalls_au32[idx]++;
  else (no)
  endif
  :l_idx_u32++;
endwhile
:return;
stop
@enduml
@startuml inline_umlgraph_23.svg
start
:l_idx_u32 = 0;
while (l_idx_u32 < SCHED_NUM_OF_TASKS) is (yes)
  :compute l_timeShift_s32;
  if (l_timeShift_s32 >= 0) then (yes)
    :call handler_();
    :NumOfTaskCalls_au32[idx]++;
  else (no)
  endif
  :l_idx_u32++;
endwhile
:return;
stop
@enduml
@startuml inline_umlgraph_24.svg
start
:l_idx_u32 = 0;
while (l_idx_u32 < SCHED_NUM_OF_TASKS) is (yes)
  :compute l_timeShift_s32;
  if (l_timeShift_s32 >= 0) then (yes)
    :call handler_();
    :NumOfTaskCalls_au32[idx]++;
  else (no)
  endif
  :l_idx_u32++;
endwhile
:return;
stop
@enduml
@startuml inline_umlgraph_25.svg
start
:l_idx_u32 = 0;
while (l_idx_u32 < SCHED_NUM_OF_TASKS) is (yes)
  :compute l_timeShift_s32;
  if (l_timeShift_s32 >= 0) then (yes)
    :call handler_();
    :NumOfTaskCalls_au32[idx]++;
  else (no)
  endif
  :l_idx_u32++;
endwhile
:return;
stop
@enduml
@startuml inline_umlgraph_26.svg
start
:l_idx_u32 = 0;
while (l_idx_u32 < SCHED_NUM_OF_TASKS) is (yes)
  :compute l_timeShift_s32;
  if (l_timeShift_s32 >= 0) then (yes)
    :call handler_();
    :NumOfTaskCalls_au32[idx]++;
  else (no)
  endif
  :l_idx_u32++;
endwhile
:return;
stop
@enduml
@startuml inline_umlgraph_27.svg
start
:l_idx_u32 = 0;
while (l_idx_u32 < SCHED_NUM_OF_TASKS) is (yes)
  :compute l_timeShift_s32;
  if (l_timeShift_s32 >= 0) then (yes)
    :call handler_();
    :NumOfTaskCalls_au32[idx]++;
  else (no)
  endif
  :l_idx_u32++;
endwhile
:return;
stop
@enduml
@startuml inline_umlgraph_28.svg
start
:l_idx_u32 = 0;
while (l_idx_u32 < SCHED_NUM_OF_TASKS) is (yes)
  :compute l_timeShift_s32;
  if (l_timeShift_s32 >= 0) then (yes)
    :call handler_();
    :NumOfTaskCalls_au32[idx]++;
  else (no)
  endif
  :l_idx_u32++;
endwhile
:return;
stop
@enduml
@startuml inline_umlgraph_29.svg
start
:l_idx_u32 = 0;
while (l_idx_u32 < SCHED_NUM_OF_TASKS) is (yes)
  :compute l_timeShift_s32;
  if (l_timeShift_s32 >= 0) then (yes)
    :call handler_();
    :NumOfTaskCalls_au32[idx]++;
  else (no)
  endif
  :l_idx_u32++;
endwhile
:return;
stop
@enduml
@startuml inline_umlgraph_30.svg
start
:l_idx_u32 = 0;
while (l_idx_u32 < SCHED_NUM_OF_TASKS) is (yes)
  :compute l_timeShift_s32;
  if (l_timeShift_s32 >= 0) then (yes)
    :call handler_();
    :NumOfTaskCalls_au32[idx]++;
  else (no)
  endif
  :l_idx_u32++;
endwhile
:return;
stop
@enduml
@startuml inline_umlgraph_31.svg
start
:l_idx_u32 = 0;
while (l_idx_u32 < SCHED_NUM_OF_TASKS) is (yes)
  :compute l_timeShift_s32;
  if (l_timeShift_s32 >= 0) then (yes)
    :call handler_();
    :NumOfTaskCalls_au32[idx]++;
  else (no)
  endif
  :l_idx_u32++;
endwhile
:return;
stop
@enduml
@startuml inline_umlgraph_32.svg
start
:l_idx_u32 = 0;
while (l_idx_u32 < SCHED_NUM_OF_TASKS) is (yes)
  :compute l_timeShift_s32;
  if (l_timeShift_s32 >= 0) then (yes)
    :call handler_();
    :NumOfTaskCalls_au32[idx]++;
  else (no)
  endif
  :l_idx_u32++;
endwhile
:return;
stop
@enduml
@startuml inline_umlgraph_33.svg
start
:l_idx_u32 = 0;
while (l_idx_u32 < SCHED_NUM_OF_TASKS) is (yes)
  :compute l_timeShift_s32;
  if (l_timeShift_s32 >= 0) then (yes)
    :call handler_();
    :NumOfTaskCalls_au32[idx]++;
  else (no)
  endif
  :l_idx_u32++;
endwhile
:return;
stop
@enduml
@startuml inline_umlgraph_34.svg
start
:l_idx_u32 = 0;
while (l_idx_u32 < SCHED_NUM_OF_TASKS) is (yes)
  :compute l_timeShift_s32;
  if (l_timeShift_s32 >= 0) then (yes)
    :call handler_();
    :NumOfTaskCalls_au32[idx]++;
  else (no)
  endif
  :l_idx_u32++;
endwhile
:return;
stop
@enduml
@startuml inline_umlgraph_35.svg
start
:l_idx_u32 = 0;
while (l_idx_u32 < SCHED_NUM_OF_TASKS) is (yes)
  :compute l_timeShift_s32;
  if (l_timeShift_s32 >= 0) then (yes)
    :call handler_();
    :NumOfTaskCalls_au32[idx]++;
  else (no)
  endif
  :l_idx_u32++;
endwhile
:return;
stop
@enduml
@startuml inline_umlgraph_36.svg
start
:l_idx_u32 = 0;
while (l_idx_u32 < SCHED_NUM_OF_TASKS) is (yes)
  :compute l_timeShift_s32;
  if (l_timeShift_s32 >= 0) then (yes)
    :call handler_();
    :NumOfTaskCalls_au32[idx]++;
  else (no)
  endif
  :l_idx_u32++;
endwhile
:return;
stop
@enduml
