/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_Sched_Priv.h"

static const char* CMockString_CountTime = "CountTime";
static const char* CMockString_DeltaTime_u32 = "DeltaTime_u32";
static const char* CMockString_Sched_Task0 = "Sched_Task0";

typedef struct _CMOCK_CountTime_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int CallOrder;

} CMOCK_CountTime_CALL_INSTANCE;

typedef struct _CMOCK_DeltaTime_u32_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint32_t ReturnVal;
  int CallOrder;

} CMOCK_DeltaTime_u32_CALL_INSTANCE;

typedef struct _CMOCK_Sched_Task0_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int CallOrder;

} CMOCK_Sched_Task0_CALL_INSTANCE;

static struct mock_Sched_PrivInstance
{
  char CountTime_IgnoreBool;
  char CountTime_CallbackBool;
  CMOCK_CountTime_CALLBACK CountTime_CallbackFunctionPointer;
  int CountTime_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE CountTime_CallInstance;
  char DeltaTime_u32_IgnoreBool;
  uint32_t DeltaTime_u32_FinalReturn;
  char DeltaTime_u32_CallbackBool;
  CMOCK_DeltaTime_u32_CALLBACK DeltaTime_u32_CallbackFunctionPointer;
  int DeltaTime_u32_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE DeltaTime_u32_CallInstance;
  char Sched_Task0_IgnoreBool;
  char Sched_Task0_CallbackBool;
  CMOCK_Sched_Task0_CALLBACK Sched_Task0_CallbackFunctionPointer;
  int Sched_Task0_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE Sched_Task0_CallInstance;
} Mock;

extern int GlobalExpectCount;
extern int GlobalVerifyOrder;

void mock_Sched_Priv_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.CountTime_CallInstance;
  if (Mock.CountTime_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_CountTime);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.CountTime_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.DeltaTime_u32_CallInstance;
  if (Mock.DeltaTime_u32_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_DeltaTime_u32);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.DeltaTime_u32_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.Sched_Task0_CallInstance;
  if (Mock.Sched_Task0_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_Sched_Task0);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.Sched_Task0_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_Sched_Priv_Init(void)
{
  mock_Sched_Priv_Destroy();
}

void mock_Sched_Priv_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
}

void CountTime(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_CountTime_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_CountTime);
  cmock_call_instance = (CMOCK_CountTime_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.CountTime_CallInstance);
  Mock.CountTime_CallInstance = CMock_Guts_MemNext(Mock.CountTime_CallInstance);
  if (Mock.CountTime_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.CountTime_CallbackBool &&
      Mock.CountTime_CallbackFunctionPointer != NULL)
  {
    Mock.CountTime_CallbackFunctionPointer(Mock.CountTime_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (Mock.CountTime_CallbackFunctionPointer != NULL)
  {
    Mock.CountTime_CallbackFunctionPointer(Mock.CountTime_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CountTime_CMockIgnore(void)
{
  Mock.CountTime_IgnoreBool = (char)1;
}

void CountTime_CMockStopIgnore(void)
{
  Mock.CountTime_IgnoreBool = (char)0;
}

void CountTime_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_CountTime_CALL_INSTANCE));
  CMOCK_CountTime_CALL_INSTANCE* cmock_call_instance = (CMOCK_CountTime_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.CountTime_CallInstance = CMock_Guts_MemChain(Mock.CountTime_CallInstance, cmock_guts_index);
  Mock.CountTime_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

void CountTime_AddCallback(CMOCK_CountTime_CALLBACK Callback)
{
  Mock.CountTime_IgnoreBool = (char)0;
  Mock.CountTime_CallbackBool = (char)1;
  Mock.CountTime_CallbackFunctionPointer = Callback;
}

void CountTime_Stub(CMOCK_CountTime_CALLBACK Callback)
{
  Mock.CountTime_IgnoreBool = (char)0;
  Mock.CountTime_CallbackBool = (char)0;
  Mock.CountTime_CallbackFunctionPointer = Callback;
}

uint32_t DeltaTime_u32(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_DeltaTime_u32_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_DeltaTime_u32);
  cmock_call_instance = (CMOCK_DeltaTime_u32_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.DeltaTime_u32_CallInstance);
  Mock.DeltaTime_u32_CallInstance = CMock_Guts_MemNext(Mock.DeltaTime_u32_CallInstance);
  if (Mock.DeltaTime_u32_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.DeltaTime_u32_FinalReturn;
    Mock.DeltaTime_u32_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.DeltaTime_u32_CallbackBool &&
      Mock.DeltaTime_u32_CallbackFunctionPointer != NULL)
  {
    uint32_t cmock_cb_ret = Mock.DeltaTime_u32_CallbackFunctionPointer(Mock.DeltaTime_u32_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (Mock.DeltaTime_u32_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.DeltaTime_u32_CallbackFunctionPointer(Mock.DeltaTime_u32_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void DeltaTime_u32_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_DeltaTime_u32_CALL_INSTANCE));
  CMOCK_DeltaTime_u32_CALL_INSTANCE* cmock_call_instance = (CMOCK_DeltaTime_u32_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.DeltaTime_u32_CallInstance = CMock_Guts_MemChain(Mock.DeltaTime_u32_CallInstance, cmock_guts_index);
  Mock.DeltaTime_u32_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.DeltaTime_u32_IgnoreBool = (char)1;
}

void DeltaTime_u32_CMockStopIgnore(void)
{
  if(Mock.DeltaTime_u32_IgnoreBool)
    Mock.DeltaTime_u32_CallInstance = CMock_Guts_MemNext(Mock.DeltaTime_u32_CallInstance);
  Mock.DeltaTime_u32_IgnoreBool = (char)0;
}

void DeltaTime_u32_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_DeltaTime_u32_CALL_INSTANCE));
  CMOCK_DeltaTime_u32_CALL_INSTANCE* cmock_call_instance = (CMOCK_DeltaTime_u32_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.DeltaTime_u32_CallInstance = CMock_Guts_MemChain(Mock.DeltaTime_u32_CallInstance, cmock_guts_index);
  Mock.DeltaTime_u32_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void DeltaTime_u32_AddCallback(CMOCK_DeltaTime_u32_CALLBACK Callback)
{
  Mock.DeltaTime_u32_IgnoreBool = (char)0;
  Mock.DeltaTime_u32_CallbackBool = (char)1;
  Mock.DeltaTime_u32_CallbackFunctionPointer = Callback;
}

void DeltaTime_u32_Stub(CMOCK_DeltaTime_u32_CALLBACK Callback)
{
  Mock.DeltaTime_u32_IgnoreBool = (char)0;
  Mock.DeltaTime_u32_CallbackBool = (char)0;
  Mock.DeltaTime_u32_CallbackFunctionPointer = Callback;
}

void Sched_Task0(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Sched_Task0_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_Sched_Task0);
  cmock_call_instance = (CMOCK_Sched_Task0_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.Sched_Task0_CallInstance);
  Mock.Sched_Task0_CallInstance = CMock_Guts_MemNext(Mock.Sched_Task0_CallInstance);
  if (Mock.Sched_Task0_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.Sched_Task0_CallbackBool &&
      Mock.Sched_Task0_CallbackFunctionPointer != NULL)
  {
    Mock.Sched_Task0_CallbackFunctionPointer(Mock.Sched_Task0_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (Mock.Sched_Task0_CallbackFunctionPointer != NULL)
  {
    Mock.Sched_Task0_CallbackFunctionPointer(Mock.Sched_Task0_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void Sched_Task0_CMockIgnore(void)
{
  Mock.Sched_Task0_IgnoreBool = (char)1;
}

void Sched_Task0_CMockStopIgnore(void)
{
  Mock.Sched_Task0_IgnoreBool = (char)0;
}

void Sched_Task0_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Sched_Task0_CALL_INSTANCE));
  CMOCK_Sched_Task0_CALL_INSTANCE* cmock_call_instance = (CMOCK_Sched_Task0_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Sched_Task0_CallInstance = CMock_Guts_MemChain(Mock.Sched_Task0_CallInstance, cmock_guts_index);
  Mock.Sched_Task0_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

void Sched_Task0_AddCallback(CMOCK_Sched_Task0_CALLBACK Callback)
{
  Mock.Sched_Task0_IgnoreBool = (char)0;
  Mock.Sched_Task0_CallbackBool = (char)1;
  Mock.Sched_Task0_CallbackFunctionPointer = Callback;
}

void Sched_Task0_Stub(CMOCK_Sched_Task0_CALLBACK Callback)
{
  Mock.Sched_Task0_IgnoreBool = (char)0;
  Mock.Sched_Task0_CallbackBool = (char)0;
  Mock.Sched_Task0_CallbackFunctionPointer = Callback;
}

