/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_MCU_H
#define _MOCK_MCU_H

#include "unity.h"
#include "Mcu.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_Mcu_Init(void);
void mock_Mcu_Destroy(void);
void mock_Mcu_Verify(void);




#define Mcu_Initialize_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("Mcu_Initialize requires _Ignore (not AndReturn)");
#define Mcu_Initialize_Ignore() Mcu_Initialize_CMockIgnore()
void Mcu_Initialize_CMockIgnore(void);
#define Mcu_Initialize_StopIgnore() Mcu_Initialize_CMockStopIgnore()
void Mcu_Initialize_CMockStopIgnore(void);
#define Mcu_Initialize_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("Mcu_Initialize requires _Expect (not AndReturn)");
#define Mcu_Initialize_Expect() Mcu_Initialize_CMockExpect(__LINE__)
void Mcu_Initialize_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_Mcu_Initialize_CALLBACK)(int cmock_num_calls);
void Mcu_Initialize_AddCallback(CMOCK_Mcu_Initialize_CALLBACK Callback);
void Mcu_Initialize_Stub(CMOCK_Mcu_Initialize_CALLBACK Callback);
#define Mcu_Initialize_StubWithCallback Mcu_Initialize_Stub
#define Mcu_ServiceWatchdogSow_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("Mcu_ServiceWatchdogSow requires _Ignore (not AndReturn)");
#define Mcu_ServiceWatchdogSow_Ignore() Mcu_ServiceWatchdogSow_CMockIgnore()
void Mcu_ServiceWatchdogSow_CMockIgnore(void);
#define Mcu_ServiceWatchdogSow_StopIgnore() Mcu_ServiceWatchdogSow_CMockStopIgnore()
void Mcu_ServiceWatchdogSow_CMockStopIgnore(void);
#define Mcu_ServiceWatchdogSow_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("Mcu_ServiceWatchdogSow requires _Expect (not AndReturn)");
#define Mcu_ServiceWatchdogSow_Expect() Mcu_ServiceWatchdogSow_CMockExpect(__LINE__)
void Mcu_ServiceWatchdogSow_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_Mcu_ServiceWatchdogSow_CALLBACK)(int cmock_num_calls);
void Mcu_ServiceWatchdogSow_AddCallback(CMOCK_Mcu_ServiceWatchdogSow_CALLBACK Callback);
void Mcu_ServiceWatchdogSow_Stub(CMOCK_Mcu_ServiceWatchdogSow_CALLBACK Callback);
#define Mcu_ServiceWatchdogSow_StubWithCallback Mcu_ServiceWatchdogSow_Stub
#define Mcu_ReloadSystick_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("Mcu_ReloadSystick requires _Ignore (not AndReturn)");
#define Mcu_ReloadSystick_Ignore() Mcu_ReloadSystick_CMockIgnore()
void Mcu_ReloadSystick_CMockIgnore(void);
#define Mcu_ReloadSystick_StopIgnore() Mcu_ReloadSystick_CMockStopIgnore()
void Mcu_ReloadSystick_CMockStopIgnore(void);
#define Mcu_ReloadSystick_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("Mcu_ReloadSystick requires _Expect (not AndReturn)");
#define Mcu_ReloadSystick_Expect() Mcu_ReloadSystick_CMockExpect(__LINE__)
void Mcu_ReloadSystick_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_Mcu_ReloadSystick_CALLBACK)(int cmock_num_calls);
void Mcu_ReloadSystick_AddCallback(CMOCK_Mcu_ReloadSystick_CALLBACK Callback);
void Mcu_ReloadSystick_Stub(CMOCK_Mcu_ReloadSystick_CALLBACK Callback);
#define Mcu_ReloadSystick_StubWithCallback Mcu_ReloadSystick_Stub
#define Mcu_GetSystemTime_u32_Ignore() TEST_FAIL_MESSAGE("Mcu_GetSystemTime_u32 requires _IgnoreAndReturn");
#define Mcu_GetSystemTime_u32_IgnoreAndReturn(cmock_retval) Mcu_GetSystemTime_u32_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void Mcu_GetSystemTime_u32_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
#define Mcu_GetSystemTime_u32_StopIgnore() Mcu_GetSystemTime_u32_CMockStopIgnore()
void Mcu_GetSystemTime_u32_CMockStopIgnore(void);
#define Mcu_GetSystemTime_u32_Expect() TEST_FAIL_MESSAGE("Mcu_GetSystemTime_u32 requires _ExpectAndReturn");
#define Mcu_GetSystemTime_u32_ExpectAndReturn(cmock_retval) Mcu_GetSystemTime_u32_CMockExpectAndReturn(__LINE__, cmock_retval)
void Mcu_GetSystemTime_u32_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
typedef uint32_t (* CMOCK_Mcu_GetSystemTime_u32_CALLBACK)(int cmock_num_calls);
void Mcu_GetSystemTime_u32_AddCallback(CMOCK_Mcu_GetSystemTime_u32_CALLBACK Callback);
void Mcu_GetSystemTime_u32_Stub(CMOCK_Mcu_GetSystemTime_u32_CALLBACK Callback);
#define Mcu_GetSystemTime_u32_StubWithCallback Mcu_GetSystemTime_u32_Stub

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
