/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_Sched_Cfg.h"

static const char* CMockString_Sched_EntrySequence = "Sched_EntrySequence";

typedef struct _CMOCK_Sched_EntrySequence_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int CallOrder;

} CMOCK_Sched_EntrySequence_CALL_INSTANCE;

static struct mock_Sched_CfgInstance
{
  char Sched_EntrySequence_IgnoreBool;
  char Sched_EntrySequence_CallbackBool;
  CMOCK_Sched_EntrySequence_CALLBACK Sched_EntrySequence_CallbackFunctionPointer;
  int Sched_EntrySequence_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE Sched_EntrySequence_CallInstance;
} Mock;

extern int GlobalExpectCount;
extern int GlobalVerifyOrder;

void mock_Sched_Cfg_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.Sched_EntrySequence_CallInstance;
  if (Mock.Sched_EntrySequence_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_Sched_EntrySequence);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.Sched_EntrySequence_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_Sched_Cfg_Init(void)
{
  mock_Sched_Cfg_Destroy();
}

void mock_Sched_Cfg_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
}

void Sched_EntrySequence(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Sched_EntrySequence_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_Sched_EntrySequence);
  cmock_call_instance = (CMOCK_Sched_EntrySequence_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.Sched_EntrySequence_CallInstance);
  Mock.Sched_EntrySequence_CallInstance = CMock_Guts_MemNext(Mock.Sched_EntrySequence_CallInstance);
  if (Mock.Sched_EntrySequence_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.Sched_EntrySequence_CallbackBool &&
      Mock.Sched_EntrySequence_CallbackFunctionPointer != NULL)
  {
    Mock.Sched_EntrySequence_CallbackFunctionPointer(Mock.Sched_EntrySequence_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (Mock.Sched_EntrySequence_CallbackFunctionPointer != NULL)
  {
    Mock.Sched_EntrySequence_CallbackFunctionPointer(Mock.Sched_EntrySequence_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void Sched_EntrySequence_CMockIgnore(void)
{
  Mock.Sched_EntrySequence_IgnoreBool = (char)1;
}

void Sched_EntrySequence_CMockStopIgnore(void)
{
  Mock.Sched_EntrySequence_IgnoreBool = (char)0;
}

void Sched_EntrySequence_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Sched_EntrySequence_CALL_INSTANCE));
  CMOCK_Sched_EntrySequence_CALL_INSTANCE* cmock_call_instance = (CMOCK_Sched_EntrySequence_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Sched_EntrySequence_CallInstance = CMock_Guts_MemChain(Mock.Sched_EntrySequence_CallInstance, cmock_guts_index);
  Mock.Sched_EntrySequence_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

void Sched_EntrySequence_AddCallback(CMOCK_Sched_EntrySequence_CALLBACK Callback)
{
  Mock.Sched_EntrySequence_IgnoreBool = (char)0;
  Mock.Sched_EntrySequence_CallbackBool = (char)1;
  Mock.Sched_EntrySequence_CallbackFunctionPointer = Callback;
}

void Sched_EntrySequence_Stub(CMOCK_Sched_EntrySequence_CALLBACK Callback)
{
  Mock.Sched_EntrySequence_IgnoreBool = (char)0;
  Mock.Sched_EntrySequence_CallbackBool = (char)0;
  Mock.Sched_EntrySequence_CallbackFunctionPointer = Callback;
}

