/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_SCHED_PRIV_H
#define _MOCK_SCHED_PRIV_H

#include "unity.h"
#include "Sched_Priv.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_Sched_Priv_Init(void);
void mock_Sched_Priv_Destroy(void);
void mock_Sched_Priv_Verify(void);




#define Sched_EntrySequence_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("Sched_EntrySequence requires _Ignore (not AndReturn)");
#define Sched_EntrySequence_Ignore() Sched_EntrySequence_CMockIgnore()
void Sched_EntrySequence_CMockIgnore(void);
#define Sched_EntrySequence_StopIgnore() Sched_EntrySequence_CMockStopIgnore()
void Sched_EntrySequence_CMockStopIgnore(void);
#define Sched_EntrySequence_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("Sched_EntrySequence requires _Expect (not AndReturn)");
#define Sched_EntrySequence_Expect() Sched_EntrySequence_CMockExpect(__LINE__)
void Sched_EntrySequence_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_Sched_EntrySequence_CALLBACK)(int cmock_num_calls);
void Sched_EntrySequence_AddCallback(CMOCK_Sched_EntrySequence_CALLBACK Callback);
void Sched_EntrySequence_Stub(CMOCK_Sched_EntrySequence_CALLBACK Callback);
#define Sched_EntrySequence_StubWithCallback Sched_EntrySequence_Stub
#define Sched_GetRefTime_u32_Ignore() TEST_FAIL_MESSAGE("Sched_GetRefTime_u32 requires _IgnoreAndReturn");
#define Sched_GetRefTime_u32_IgnoreAndReturn(cmock_retval) Sched_GetRefTime_u32_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void Sched_GetRefTime_u32_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
#define Sched_GetRefTime_u32_StopIgnore() Sched_GetRefTime_u32_CMockStopIgnore()
void Sched_GetRefTime_u32_CMockStopIgnore(void);
#define Sched_GetRefTime_u32_Expect() TEST_FAIL_MESSAGE("Sched_GetRefTime_u32 requires _ExpectAndReturn");
#define Sched_GetRefTime_u32_ExpectAndReturn(cmock_retval) Sched_GetRefTime_u32_CMockExpectAndReturn(__LINE__, cmock_retval)
void Sched_GetRefTime_u32_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
typedef uint32_t (* CMOCK_Sched_GetRefTime_u32_CALLBACK)(int cmock_num_calls);
void Sched_GetRefTime_u32_AddCallback(CMOCK_Sched_GetRefTime_u32_CALLBACK Callback);
void Sched_GetRefTime_u32_Stub(CMOCK_Sched_GetRefTime_u32_CALLBACK Callback);
#define Sched_GetRefTime_u32_StubWithCallback Sched_GetRefTime_u32_Stub
#define CountTime_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("CountTime requires _Ignore (not AndReturn)");
#define CountTime_Ignore() CountTime_CMockIgnore()
void CountTime_CMockIgnore(void);
#define CountTime_StopIgnore() CountTime_CMockStopIgnore()
void CountTime_CMockStopIgnore(void);
#define CountTime_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("CountTime requires _Expect (not AndReturn)");
#define CountTime_Expect() CountTime_CMockExpect(__LINE__)
void CountTime_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_CountTime_CALLBACK)(int cmock_num_calls);
void CountTime_AddCallback(CMOCK_CountTime_CALLBACK Callback);
void CountTime_Stub(CMOCK_CountTime_CALLBACK Callback);
#define CountTime_StubWithCallback CountTime_Stub
#define ExecutePendingTasks_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("ExecutePendingTasks requires _Ignore (not AndReturn)");
#define ExecutePendingTasks_Ignore() ExecutePendingTasks_CMockIgnore()
void ExecutePendingTasks_CMockIgnore(void);
#define ExecutePendingTasks_StopIgnore() ExecutePendingTasks_CMockStopIgnore()
void ExecutePendingTasks_CMockStopIgnore(void);
#define ExecutePendingTasks_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("ExecutePendingTasks requires _Expect (not AndReturn)");
#define ExecutePendingTasks_Expect() ExecutePendingTasks_CMockExpect(__LINE__)
void ExecutePendingTasks_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_ExecutePendingTasks_CALLBACK)(int cmock_num_calls);
void ExecutePendingTasks_AddCallback(CMOCK_ExecutePendingTasks_CALLBACK Callback);
void ExecutePendingTasks_Stub(CMOCK_ExecutePendingTasks_CALLBACK Callback);
#define ExecutePendingTasks_StubWithCallback ExecutePendingTasks_Stub
#define DeltaTime_u32_Ignore() TEST_FAIL_MESSAGE("DeltaTime_u32 requires _IgnoreAndReturn");
#define DeltaTime_u32_IgnoreAndReturn(cmock_retval) DeltaTime_u32_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void DeltaTime_u32_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
#define DeltaTime_u32_StopIgnore() DeltaTime_u32_CMockStopIgnore()
void DeltaTime_u32_CMockStopIgnore(void);
#define DeltaTime_u32_Expect() TEST_FAIL_MESSAGE("DeltaTime_u32 requires _ExpectAndReturn");
#define DeltaTime_u32_ExpectAndReturn(cmock_retval) DeltaTime_u32_CMockExpectAndReturn(__LINE__, cmock_retval)
void DeltaTime_u32_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
typedef uint32_t (* CMOCK_DeltaTime_u32_CALLBACK)(int cmock_num_calls);
void DeltaTime_u32_AddCallback(CMOCK_DeltaTime_u32_CALLBACK Callback);
void DeltaTime_u32_Stub(CMOCK_DeltaTime_u32_CALLBACK Callback);
#define DeltaTime_u32_StubWithCallback DeltaTime_u32_Stub
#define Sched_Task0_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("Sched_Task0 requires _Ignore (not AndReturn)");
#define Sched_Task0_Ignore() Sched_Task0_CMockIgnore()
void Sched_Task0_CMockIgnore(void);
#define Sched_Task0_StopIgnore() Sched_Task0_CMockStopIgnore()
void Sched_Task0_CMockStopIgnore(void);
#define Sched_Task0_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("Sched_Task0 requires _Expect (not AndReturn)");
#define Sched_Task0_Expect() Sched_Task0_CMockExpect(__LINE__)
void Sched_Task0_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_Sched_Task0_CALLBACK)(int cmock_num_calls);
void Sched_Task0_AddCallback(CMOCK_Sched_Task0_CALLBACK Callback);
void Sched_Task0_Stub(CMOCK_Sched_Task0_CALLBACK Callback);
#define Sched_Task0_StubWithCallback Sched_Task0_Stub
#define Sched_Task2_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("Sched_Task2 requires _Ignore (not AndReturn)");
#define Sched_Task2_Ignore() Sched_Task2_CMockIgnore()
void Sched_Task2_CMockIgnore(void);
#define Sched_Task2_StopIgnore() Sched_Task2_CMockStopIgnore()
void Sched_Task2_CMockStopIgnore(void);
#define Sched_Task2_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("Sched_Task2 requires _Expect (not AndReturn)");
#define Sched_Task2_Expect() Sched_Task2_CMockExpect(__LINE__)
void Sched_Task2_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_Sched_Task2_CALLBACK)(int cmock_num_calls);
void Sched_Task2_AddCallback(CMOCK_Sched_Task2_CALLBACK Callback);
void Sched_Task2_Stub(CMOCK_Sched_Task2_CALLBACK Callback);
#define Sched_Task2_StubWithCallback Sched_Task2_Stub
#define Sched_Task3_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("Sched_Task3 requires _Ignore (not AndReturn)");
#define Sched_Task3_Ignore() Sched_Task3_CMockIgnore()
void Sched_Task3_CMockIgnore(void);
#define Sched_Task3_StopIgnore() Sched_Task3_CMockStopIgnore()
void Sched_Task3_CMockStopIgnore(void);
#define Sched_Task3_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("Sched_Task3 requires _Expect (not AndReturn)");
#define Sched_Task3_Expect() Sched_Task3_CMockExpect(__LINE__)
void Sched_Task3_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_Sched_Task3_CALLBACK)(int cmock_num_calls);
void Sched_Task3_AddCallback(CMOCK_Sched_Task3_CALLBACK Callback);
void Sched_Task3_Stub(CMOCK_Sched_Task3_CALLBACK Callback);
#define Sched_Task3_StubWithCallback Sched_Task3_Stub

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
