/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_Sched_Priv.h"

static const char* CMockString_DeltaTime_u32 = "DeltaTime_u32";
static const char* CMockString_ExecutePendingTasks = "ExecutePendingTasks";
static const char* CMockString_Sched_Task0 = "Sched_Task0";
static const char* CMockString_Sched_Task1 = "Sched_Task1";
static const char* CMockString_Sched_Task2 = "Sched_Task2";
static const char* CMockString_Sched_Task3 = "Sched_Task3";

typedef struct _CMOCK_ExecutePendingTasks_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int CallOrder;

} CMOCK_ExecutePendingTasks_CALL_INSTANCE;

typedef struct _CMOCK_DeltaTime_u32_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint32_t ReturnVal;
  int CallOrder;

} CMOCK_DeltaTime_u32_CALL_INSTANCE;

typedef struct _CMOCK_Sched_Task0_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int CallOrder;

} CMOCK_Sched_Task0_CALL_INSTANCE;

typedef struct _CMOCK_Sched_Task1_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int CallOrder;

} CMOCK_Sched_Task1_CALL_INSTANCE;

typedef struct _CMOCK_Sched_Task2_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int CallOrder;

} CMOCK_Sched_Task2_CALL_INSTANCE;

typedef struct _CMOCK_Sched_Task3_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int CallOrder;

} CMOCK_Sched_Task3_CALL_INSTANCE;

static struct mock_Sched_PrivInstance
{
  char ExecutePendingTasks_IgnoreBool;
  char ExecutePendingTasks_CallbackBool;
  CMOCK_ExecutePendingTasks_CALLBACK ExecutePendingTasks_CallbackFunctionPointer;
  int ExecutePendingTasks_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE ExecutePendingTasks_CallInstance;
  char DeltaTime_u32_IgnoreBool;
  uint32_t DeltaTime_u32_FinalReturn;
  char DeltaTime_u32_CallbackBool;
  CMOCK_DeltaTime_u32_CALLBACK DeltaTime_u32_CallbackFunctionPointer;
  int DeltaTime_u32_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE DeltaTime_u32_CallInstance;
  char Sched_Task0_IgnoreBool;
  char Sched_Task0_CallbackBool;
  CMOCK_Sched_Task0_CALLBACK Sched_Task0_CallbackFunctionPointer;
  int Sched_Task0_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE Sched_Task0_CallInstance;
  char Sched_Task1_IgnoreBool;
  char Sched_Task1_CallbackBool;
  CMOCK_Sched_Task1_CALLBACK Sched_Task1_CallbackFunctionPointer;
  int Sched_Task1_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE Sched_Task1_CallInstance;
  char Sched_Task2_IgnoreBool;
  char Sched_Task2_CallbackBool;
  CMOCK_Sched_Task2_CALLBACK Sched_Task2_CallbackFunctionPointer;
  int Sched_Task2_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE Sched_Task2_CallInstance;
  char Sched_Task3_IgnoreBool;
  char Sched_Task3_CallbackBool;
  CMOCK_Sched_Task3_CALLBACK Sched_Task3_CallbackFunctionPointer;
  int Sched_Task3_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE Sched_Task3_CallInstance;
} Mock;

extern int GlobalExpectCount;
extern int GlobalVerifyOrder;

void mock_Sched_Priv_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.ExecutePendingTasks_CallInstance;
  if (Mock.ExecutePendingTasks_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_ExecutePendingTasks);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.ExecutePendingTasks_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.DeltaTime_u32_CallInstance;
  if (Mock.DeltaTime_u32_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_DeltaTime_u32);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.DeltaTime_u32_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.Sched_Task0_CallInstance;
  if (Mock.Sched_Task0_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_Sched_Task0);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.Sched_Task0_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.Sched_Task1_CallInstance;
  if (Mock.Sched_Task1_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_Sched_Task1);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.Sched_Task1_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.Sched_Task2_CallInstance;
  if (Mock.Sched_Task2_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_Sched_Task2);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.Sched_Task2_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.Sched_Task3_CallInstance;
  if (Mock.Sched_Task3_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_Sched_Task3);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.Sched_Task3_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_Sched_Priv_Init(void)
{
  mock_Sched_Priv_Destroy();
}

void mock_Sched_Priv_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
}

void ExecutePendingTasks(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_ExecutePendingTasks_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_ExecutePendingTasks);
  cmock_call_instance = (CMOCK_ExecutePendingTasks_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.ExecutePendingTasks_CallInstance);
  Mock.ExecutePendingTasks_CallInstance = CMock_Guts_MemNext(Mock.ExecutePendingTasks_CallInstance);
  if (Mock.ExecutePendingTasks_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.ExecutePendingTasks_CallbackBool &&
      Mock.ExecutePendingTasks_CallbackFunctionPointer != NULL)
  {
    Mock.ExecutePendingTasks_CallbackFunctionPointer(Mock.ExecutePendingTasks_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (Mock.ExecutePendingTasks_CallbackFunctionPointer != NULL)
  {
    Mock.ExecutePendingTasks_CallbackFunctionPointer(Mock.ExecutePendingTasks_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void ExecutePendingTasks_CMockIgnore(void)
{
  Mock.ExecutePendingTasks_IgnoreBool = (char)1;
}

void ExecutePendingTasks_CMockStopIgnore(void)
{
  Mock.ExecutePendingTasks_IgnoreBool = (char)0;
}

void ExecutePendingTasks_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ExecutePendingTasks_CALL_INSTANCE));
  CMOCK_ExecutePendingTasks_CALL_INSTANCE* cmock_call_instance = (CMOCK_ExecutePendingTasks_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ExecutePendingTasks_CallInstance = CMock_Guts_MemChain(Mock.ExecutePendingTasks_CallInstance, cmock_guts_index);
  Mock.ExecutePendingTasks_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

void ExecutePendingTasks_AddCallback(CMOCK_ExecutePendingTasks_CALLBACK Callback)
{
  Mock.ExecutePendingTasks_IgnoreBool = (char)0;
  Mock.ExecutePendingTasks_CallbackBool = (char)1;
  Mock.ExecutePendingTasks_CallbackFunctionPointer = Callback;
}

void ExecutePendingTasks_Stub(CMOCK_ExecutePendingTasks_CALLBACK Callback)
{
  Mock.ExecutePendingTasks_IgnoreBool = (char)0;
  Mock.ExecutePendingTasks_CallbackBool = (char)0;
  Mock.ExecutePendingTasks_CallbackFunctionPointer = Callback;
}

uint32_t DeltaTime_u32(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_DeltaTime_u32_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_DeltaTime_u32);
  cmock_call_instance = (CMOCK_DeltaTime_u32_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.DeltaTime_u32_CallInstance);
  Mock.DeltaTime_u32_CallInstance = CMock_Guts_MemNext(Mock.DeltaTime_u32_CallInstance);
  if (Mock.DeltaTime_u32_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.DeltaTime_u32_FinalReturn;
    Mock.DeltaTime_u32_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.DeltaTime_u32_CallbackBool &&
      Mock.DeltaTime_u32_CallbackFunctionPointer != NULL)
  {
    uint32_t cmock_cb_ret = Mock.DeltaTime_u32_CallbackFunctionPointer(Mock.DeltaTime_u32_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (Mock.DeltaTime_u32_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.DeltaTime_u32_CallbackFunctionPointer(Mock.DeltaTime_u32_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void DeltaTime_u32_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_DeltaTime_u32_CALL_INSTANCE));
  CMOCK_DeltaTime_u32_CALL_INSTANCE* cmock_call_instance = (CMOCK_DeltaTime_u32_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.DeltaTime_u32_CallInstance = CMock_Guts_MemChain(Mock.DeltaTime_u32_CallInstance, cmock_guts_index);
  Mock.DeltaTime_u32_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.DeltaTime_u32_IgnoreBool = (char)1;
}

void DeltaTime_u32_CMockStopIgnore(void)
{
  if(Mock.DeltaTime_u32_IgnoreBool)
    Mock.DeltaTime_u32_CallInstance = CMock_Guts_MemNext(Mock.DeltaTime_u32_CallInstance);
  Mock.DeltaTime_u32_IgnoreBool = (char)0;
}

void DeltaTime_u32_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_DeltaTime_u32_CALL_INSTANCE));
  CMOCK_DeltaTime_u32_CALL_INSTANCE* cmock_call_instance = (CMOCK_DeltaTime_u32_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.DeltaTime_u32_CallInstance = CMock_Guts_MemChain(Mock.DeltaTime_u32_CallInstance, cmock_guts_index);
  Mock.DeltaTime_u32_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void DeltaTime_u32_AddCallback(CMOCK_DeltaTime_u32_CALLBACK Callback)
{
  Mock.DeltaTime_u32_IgnoreBool = (char)0;
  Mock.DeltaTime_u32_CallbackBool = (char)1;
  Mock.DeltaTime_u32_CallbackFunctionPointer = Callback;
}

void DeltaTime_u32_Stub(CMOCK_DeltaTime_u32_CALLBACK Callback)
{
  Mock.DeltaTime_u32_IgnoreBool = (char)0;
  Mock.DeltaTime_u32_CallbackBool = (char)0;
  Mock.DeltaTime_u32_CallbackFunctionPointer = Callback;
}

void Sched_Task0(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Sched_Task0_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_Sched_Task0);
  cmock_call_instance = (CMOCK_Sched_Task0_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.Sched_Task0_CallInstance);
  Mock.Sched_Task0_CallInstance = CMock_Guts_MemNext(Mock.Sched_Task0_CallInstance);
  if (Mock.Sched_Task0_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.Sched_Task0_CallbackBool &&
      Mock.Sched_Task0_CallbackFunctionPointer != NULL)
  {
    Mock.Sched_Task0_CallbackFunctionPointer(Mock.Sched_Task0_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (Mock.Sched_Task0_CallbackFunctionPointer != NULL)
  {
    Mock.Sched_Task0_CallbackFunctionPointer(Mock.Sched_Task0_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void Sched_Task0_CMockIgnore(void)
{
  Mock.Sched_Task0_IgnoreBool = (char)1;
}

void Sched_Task0_CMockStopIgnore(void)
{
  Mock.Sched_Task0_IgnoreBool = (char)0;
}

void Sched_Task0_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Sched_Task0_CALL_INSTANCE));
  CMOCK_Sched_Task0_CALL_INSTANCE* cmock_call_instance = (CMOCK_Sched_Task0_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Sched_Task0_CallInstance = CMock_Guts_MemChain(Mock.Sched_Task0_CallInstance, cmock_guts_index);
  Mock.Sched_Task0_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

void Sched_Task0_AddCallback(CMOCK_Sched_Task0_CALLBACK Callback)
{
  Mock.Sched_Task0_IgnoreBool = (char)0;
  Mock.Sched_Task0_CallbackBool = (char)1;
  Mock.Sched_Task0_CallbackFunctionPointer = Callback;
}

void Sched_Task0_Stub(CMOCK_Sched_Task0_CALLBACK Callback)
{
  Mock.Sched_Task0_IgnoreBool = (char)0;
  Mock.Sched_Task0_CallbackBool = (char)0;
  Mock.Sched_Task0_CallbackFunctionPointer = Callback;
}

void Sched_Task1(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Sched_Task1_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_Sched_Task1);
  cmock_call_instance = (CMOCK_Sched_Task1_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.Sched_Task1_CallInstance);
  Mock.Sched_Task1_CallInstance = CMock_Guts_MemNext(Mock.Sched_Task1_CallInstance);
  if (Mock.Sched_Task1_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.Sched_Task1_CallbackBool &&
      Mock.Sched_Task1_CallbackFunctionPointer != NULL)
  {
    Mock.Sched_Task1_CallbackFunctionPointer(Mock.Sched_Task1_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (Mock.Sched_Task1_CallbackFunctionPointer != NULL)
  {
    Mock.Sched_Task1_CallbackFunctionPointer(Mock.Sched_Task1_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void Sched_Task1_CMockIgnore(void)
{
  Mock.Sched_Task1_IgnoreBool = (char)1;
}

void Sched_Task1_CMockStopIgnore(void)
{
  Mock.Sched_Task1_IgnoreBool = (char)0;
}

void Sched_Task1_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Sched_Task1_CALL_INSTANCE));
  CMOCK_Sched_Task1_CALL_INSTANCE* cmock_call_instance = (CMOCK_Sched_Task1_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Sched_Task1_CallInstance = CMock_Guts_MemChain(Mock.Sched_Task1_CallInstance, cmock_guts_index);
  Mock.Sched_Task1_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

void Sched_Task1_AddCallback(CMOCK_Sched_Task1_CALLBACK Callback)
{
  Mock.Sched_Task1_IgnoreBool = (char)0;
  Mock.Sched_Task1_CallbackBool = (char)1;
  Mock.Sched_Task1_CallbackFunctionPointer = Callback;
}

void Sched_Task1_Stub(CMOCK_Sched_Task1_CALLBACK Callback)
{
  Mock.Sched_Task1_IgnoreBool = (char)0;
  Mock.Sched_Task1_CallbackBool = (char)0;
  Mock.Sched_Task1_CallbackFunctionPointer = Callback;
}

void Sched_Task2(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Sched_Task2_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_Sched_Task2);
  cmock_call_instance = (CMOCK_Sched_Task2_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.Sched_Task2_CallInstance);
  Mock.Sched_Task2_CallInstance = CMock_Guts_MemNext(Mock.Sched_Task2_CallInstance);
  if (Mock.Sched_Task2_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.Sched_Task2_CallbackBool &&
      Mock.Sched_Task2_CallbackFunctionPointer != NULL)
  {
    Mock.Sched_Task2_CallbackFunctionPointer(Mock.Sched_Task2_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (Mock.Sched_Task2_CallbackFunctionPointer != NULL)
  {
    Mock.Sched_Task2_CallbackFunctionPointer(Mock.Sched_Task2_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void Sched_Task2_CMockIgnore(void)
{
  Mock.Sched_Task2_IgnoreBool = (char)1;
}

void Sched_Task2_CMockStopIgnore(void)
{
  Mock.Sched_Task2_IgnoreBool = (char)0;
}

void Sched_Task2_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Sched_Task2_CALL_INSTANCE));
  CMOCK_Sched_Task2_CALL_INSTANCE* cmock_call_instance = (CMOCK_Sched_Task2_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Sched_Task2_CallInstance = CMock_Guts_MemChain(Mock.Sched_Task2_CallInstance, cmock_guts_index);
  Mock.Sched_Task2_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

void Sched_Task2_AddCallback(CMOCK_Sched_Task2_CALLBACK Callback)
{
  Mock.Sched_Task2_IgnoreBool = (char)0;
  Mock.Sched_Task2_CallbackBool = (char)1;
  Mock.Sched_Task2_CallbackFunctionPointer = Callback;
}

void Sched_Task2_Stub(CMOCK_Sched_Task2_CALLBACK Callback)
{
  Mock.Sched_Task2_IgnoreBool = (char)0;
  Mock.Sched_Task2_CallbackBool = (char)0;
  Mock.Sched_Task2_CallbackFunctionPointer = Callback;
}

void Sched_Task3(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Sched_Task3_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_Sched_Task3);
  cmock_call_instance = (CMOCK_Sched_Task3_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.Sched_Task3_CallInstance);
  Mock.Sched_Task3_CallInstance = CMock_Guts_MemNext(Mock.Sched_Task3_CallInstance);
  if (Mock.Sched_Task3_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.Sched_Task3_CallbackBool &&
      Mock.Sched_Task3_CallbackFunctionPointer != NULL)
  {
    Mock.Sched_Task3_CallbackFunctionPointer(Mock.Sched_Task3_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (Mock.Sched_Task3_CallbackFunctionPointer != NULL)
  {
    Mock.Sched_Task3_CallbackFunctionPointer(Mock.Sched_Task3_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void Sched_Task3_CMockIgnore(void)
{
  Mock.Sched_Task3_IgnoreBool = (char)1;
}

void Sched_Task3_CMockStopIgnore(void)
{
  Mock.Sched_Task3_IgnoreBool = (char)0;
}

void Sched_Task3_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Sched_Task3_CALL_INSTANCE));
  CMOCK_Sched_Task3_CALL_INSTANCE* cmock_call_instance = (CMOCK_Sched_Task3_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Sched_Task3_CallInstance = CMock_Guts_MemChain(Mock.Sched_Task3_CallInstance, cmock_guts_index);
  Mock.Sched_Task3_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

void Sched_Task3_AddCallback(CMOCK_Sched_Task3_CALLBACK Callback)
{
  Mock.Sched_Task3_IgnoreBool = (char)0;
  Mock.Sched_Task3_CallbackBool = (char)1;
  Mock.Sched_Task3_CallbackFunctionPointer = Callback;
}

void Sched_Task3_Stub(CMOCK_Sched_Task3_CALLBACK Callback)
{
  Mock.Sched_Task3_IgnoreBool = (char)0;
  Mock.Sched_Task3_CallbackBool = (char)0;
  Mock.Sched_Task3_CallbackFunctionPointer = Callback;
}

